### ISSUE TITLE
Mixins without the decorator

### ISSUE THREAD

**Issue by abel-n** [emberjs/ember-classic-decorator#35]
I've found that extending models and routes (haven't tested with anything else yet) _with_ a mixin mixed in doesn't throw an error and seems to work just fine.
```js
export default class XModel extends Model.extend(XMixin) {}
```
In docs it states
> In order to remove the classic decorator from a class, you must:
> * Remove usage of mixins from the class

So now I'm confused whether I should introduce `@classic` on these classes or not.

Bonus question: About utility classes docs state:
> Certain classes must always be marked as classic:
> * Utility classes that extend directly from `EmberObject`
>
> To remove the `@classic` decorator from them, you can:
> * Rewrite utility classes so they do not extend from `EmberObject` at all, and only use native class syntax.

So does that mean that a class needs `@classic` only if it extends `EmberObject` _directly_ or if any of its ancestors extends it?

**Comment by pzuraq** [comment]
You should be using `@classic` on these classes. The point of the decorator is, in part, to prepare your app for a world without these features, so they can be deprecated and removed in Ember (and so you won't have to rewrite any code when that happens). 

In order to remove it, Ember Data will have to provide a new API for polymorphism. This will probably take some time, so in the meantime the decorator will continue to exist, and provide a reminder about this edge case.

**Comment by abel-n** [comment]
Thank you very much, I believe that answered all my questions. :bowing_man:
