### ISSUE TITLE
Generates broken code in production

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember-classic-decorator#85]
[Here is a reproduction](https://github.com/boris-petrov/babel-bug). Ignore the repo name, initially I thought this is a Babel bug because I couldn't imagine what else could be doing that. But it's `ember-classic-decorator`.

Clone the repo, `npm install`, `ember serve --environment=production`. Then, in `dist/assets/babel-bug-*.js` you'll see `undefined !== this.bar`. The original is `cols[0]?.bar !== this.bar`. I've no idea who or why it changes this but this is a major problem.

**Comment by ef4** [comment]
Your repo name turns out to be correct anyway, because this is a babel bug. 😄

The bug is triggered not directly by ember-classic-decorator, but because ember-classic-decorator installs @embroider/macros and @embroider/macros uses Babel's `path.evaluate()`, and using your reproduction I found this bug in `path.evaluate()`:

https://github.com/babel/babel/issues/14197

**Comment by boris-petrov** [comment]
Thanks for taking the time to look into it! :) Should we close this issue here then?
